trigger: none  # Manual trigger only

parameters:
- name: AssignmentID
  displayName: 'Enter Assignment ID'
  type: string

variables:
- name: apiToken
  value: $(apiToken)  # Reference to a secret variable

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Dev
  displayName: 'Deploy to Dev'
  jobs:
  - deployment: DeployDev
    environment: Dev
    strategy:
      runOnce:
       deploy:
          steps:
           - script: |
                         echo "Deploying to Dev with Assignment ID : ${{ parameters.AssignmentID }}"
                         
                          $headers = @{
                                              "Authorization" = "$(CES_TOKEN)"
                                              "Content-Type" = "application/json"
                                          }

                                          $body = @{
                                              "runtimeConfiguration" = "$(CP_RUNTIME)"
                                          } | ConvertTo-Json -Depth 10

                                          $url = "$(CES_URL)/ispw/$(CP_RUNTIME)/assignments/$(assignment_id)/close"

                                          Write-Host "Calling CES API: $url"
                                          Invoke-WebRequest -Uri $url `
                                                            -Method POST `
                                                            -Headers $headers `
                                                            -Body $body `
                                                            -ContentType "application/json"

- stage: QA
  displayName: 'Deploy to QA'
  dependsOn: Dev
  condition: succeeded()
  jobs:
  - deployment: DeployQA
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
                       echo "Deploying to QA with Assignment ID : ${{ parameters.AssignmentID }}"

- stage: Prod
  displayName: 'Deploy to Prod'
  dependsOn: QA
  condition: succeeded()
  jobs:
  - deployment: DeployProd
    environment: Prod
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
                       echo "Deploying to Prod with Assignment ID : ${{ parameters.AssignmentID }}"
