
name: Test Jira

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Proceed'
        required: true
        default: 'Yes'
        type: choice
        options:
          - Yes
          - No

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Test-JIRA:
    # The type of runner that the job will run on
    runs-on: [ISPW]
    steps:
    # Runs a set of commands using the runners shell
    - name: Get Issue Info
      shell: pwsh
      run: |

            $User = "eraso.xavier@gmail.com"
            $Token = "${{ secrets.PERSONAL_JIRA_TOKEN }}"  # Replace with your actual API token
            $EncodedAuth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("${User}:${Token}"))

    - name: Update Issue Comment
      shell: pwsh
      run: |
            $User = "eraso.xavier@gmail.com"
            $Token = "${{ secrets.PERSONAL_JIRA_TOKEN }}"  # Replace with your actual API token
            $EncodedAuth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("${User}:${Token}"))
    
            # Prepare the request body in JSON format
            $body = @{
                body = @{
                    type = "doc"
                    version = 1
                    content = @(
                        @{
                            type = "paragraph"
                            content = @(
                                if ("${{vars.LANGUAGE}}" -eq "EN") {
                                    @{
                                        type = "text"
                                        text = "The assignment TEST has been created for this feature"
                                    }
                                }
                                else {
                                    @{
                                        type = "text"
                                        text = "L'assignment TEST a été créé pour cette user story"
                                    }
                                }
                            )
                        }
                    )
                }
            } | ConvertTo-Json -Depth 5 -Compress

            # Display the JSON body for debugging purposes
            Write-Host "Request body: $body"

            # Send the POST request to Jira API
            $response = Invoke-WebRequest -Uri 'https://erasoxavier.atlassian.net/rest/api/3/issue/SCRUM-1/comment' `
                -Method POST `
                -Headers @{
                    'Accept' = 'application/json'
                    'Authorization' = "Basic $EncodedAuth"
                } `
                -Body $body `
                -ContentType 'application/json'


